name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: EC2에 접속해서 git pull 실행하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 주의: 아래 경로를 실제 EC2에 git clone 해둔 폴더 경로로 꼭 수정하세요!
            cd /home/ubuntu/vulnapp
            git pull origin main